### ISSUE TITLE
这个网站的能不能实现？

### ISSUE THREAD

**Issue by BadDeveloper2022** [0zhouquan0/QQ_LoginTest#1]
https://passport.qidian.com/?returnurl=https%3A%2F%2Fwww.qidian.com%2FloginSuccess%3Fsurl%3Dhttps%253A%252F%252Fwww.qidian.com%252F&popup=1&ticket=1&target=iframe&areaid=1&appid=10&auto=1&autotime=30&version=1.0

**Comment by quan0zhou** [comment]
例如 原图地址：https://ssl.captcha.qq.com/cap_union_new_getcapbysig?aid=1600000770&asig=&captype=7&protocol=https&clientype=2&disturblevel=1&apptype=1&curenv=inner&ua=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV09XNjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS82NS4wLjMzMjUuMzIgU2FmYXJpLzUzNy4zNg==&sess=_VN3Hl6rbmCXjCREJl0zqAtU14gQ8jVixP9sYfk20PrDsilSt-AWpHuHT1vc9-XCYyJ69F2hCjVdHqJlmXi0-g_PpOw7XCMtaWiMHzVCgDjavumx2LNVztbcnqsuq5NOl6t6aNF2PLUsDS7jVM0bEh95CaNHTluTuLODUi_SlOpjDP9angf2x86RGR38buvA&theme=&sid=6520053285213128093&noBorder=noborder&fb=1&forcestyle=undefined&showtype=embed&uid=&cap_cd=&lang=2052&rnd=967970&rand=0.6182048662457742&vsig=c012AFGtZgcwaKIXJjru3KhNBOah6sUc_eiI6sNwhh_KXEjKT71dpg8SDavFkr7Y5lEDfPvE3Wvq-VHS4TuSYU7tJAhm72m04lz1VwQdiGTKhCZ_mV126aIiqDTDgstUoeqTdBZMSD7FVNXqn9jBNWwWY-mU1sCzMhFWkNVzxswHRw*&img_index=0
缺块地址：https://ssl.captcha.qq.com/cap_union_new_getcapbysig?aid=1600000770&asig=&captype=7&protocol=https&clientype=2&disturblevel=1&apptype=1&curenv=inner&ua=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV09XNjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS82NS4wLjMzMjUuMzIgU2FmYXJpLzUzNy4zNg==&sess=_VN3Hl6rbmCXjCREJl0zqAtU14gQ8jVixP9sYfk20PrDsilSt-AWpHuHT1vc9-XCYyJ69F2hCjVdHqJlmXi0-g_PpOw7XCMtaWiMHzVCgDjavumx2LNVztbcnqsuq5NOl6t6aNF2PLUsDS7jVM0bEh95CaNHTluTuLODUi_SlOpjDP9angf2x86RGR38buvA&theme=&sid=6520053285213128093&noBorder=noborder&fb=1&forcestyle=undefined&showtype=embed&uid=&cap_cd=&lang=2052&rnd=967970&rand=0.6182048662457742&vsig=c012AFGtZgcwaKIXJjru3KhNBOah6sUc_eiI6sNwhh_KXEjKT71dpg8SDavFkr7Y5lEDfPvE3Wvq-VHS4TuSYU7tJAhm72m04lz1VwQdiGTKhCZ_mV126aIiqDTDgstUoeqTdBZMSD7FVNXqn9jBNWwWY-mU1sCzMhFWkNVzxswHRw*&img_index=1
然后拿来比较对比，可以计算出应该滑动的偏移距离

**Comment by BadDeveloper2022** [comment]
已经实现了，谢谢分享
